name: spec-ci
on: [push, pull_request]
jobs:
  lint-openapi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm i -g @redocly/cli
      - run: redocly lint docs/openapi.yaml
